# Generated by Django 2.2.2 on 2019-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tag_line', models.CharField(max_length=255)),
                ('ticket_Price', models.PositiveIntegerField()),
                ('disc', models.CharField(max_length=1000)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time_of_event', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
